services:
  wsaf-postgres:
    extends:
      file: docker-compose.yml
      service: wsaf-postgres
    container_name: wsaf25-postgres-dev
    ports:
      - "44363:5432"

  wsaf25-website:
    extends:
      file: docker-compose.yml
      service: wsaf25-website
    container_name: wsaf25-website-dev

  # wsaf-management:
  #   extends:
  #     file: docker-compose.yml
  #     service: wsaf-management
  #   container_name: wsaf25-management-dev
  #   environment:
  #     USE_X_FORWARDED_HOST: "True"
  #     DEBUG: ${WSAF_MANAGEMENT_DEV_DEBUG}

  wsaf-assets:
    extends:
      file: docker-compose.yml
      service: wsaf-assets
    container_name: wsaf25-assets-dev

volumes:
  wsaf-postgres:
  wsaf-management-media:
    external:
      name: wsaf-management-media

networks:
  wsaf-network:
